// Re-export everything from the orchestrator package
export {
  // Core orchestration
  loadConfig,
  loadConfigAsync,
  type AiSdlcConfig,
  validateIssue,
  validateIssueWithExtensions,
  parseComplexity,
  executePipeline,
  type ExecuteOptions,
  type PipelineResult,
  type PromotionResult,
  validateAgentOutput,
  type ValidationContext,
  type ValidationResult,
  type ValidationViolation,
  createLogger,
  type Logger,
  executeFixCI,
  countRetryAttempts,
  fetchCILogs,
  type FixCIOptions,

  // Shared utilities
  getGitHubConfig,
  resolveRepoRoot,
  createDefaultAuditLog,
  resolveAutonomyLevel,
  resolveConstraints,
  mergeBlockedPaths,
  isAutonomousStrategy,
  recordMetric,
  validateAndAuditOutput,
  createPipelineMemory,
  evaluatePipelineCompliance,
  authorizeFilesChanged,
  extractIssueNumber,
  BRANCH_PATTERN,
  type GitHubEnvConfig,
  type ValidateAndAuditParams,

  // Defaults
  DEFAULT_CONFIG_DIR_NAME,

  // Security subsystem
  createPipelineSecurity,
  checkKillSwitch,
  issueAgentCredentials,
  revokeAgentCredentials,
  classifyAndSubmitApproval,
  classifyApprovalTier,
  compareTiers,
  createGitHubSandbox,
  createGitHubJITCredentialIssuer,
  createGitHubSandboxProvider,
  createGitHubJITProvider,
  type SecurityContext,

  // Provenance tracking
  createPipelineProvenance,
  attachProvenanceToPR,
  validatePipelineProvenance,
  provenanceToAnnotations,
  provenanceFromAnnotations,
  PROVENANCE_ANNOTATION_PREFIX,
  type ProvenanceRecord,
  type ReviewDecision,

  // Admission pipeline
  createPipelineAdmission,
  admitIssueResource,
  type PipelineAdmissionConfig,
  type AdmissionPipeline,
  type AdmissionResult,

  // Metrics instrumentation
  createPipelineMetricStore,
  createInstrumentedEnforcement,
  createInstrumentedAutonomy,
  createInstrumentedExecutor,
  STANDARD_METRICS,
  instrumentExecutor,

  // Agent discovery
  createPipelineDiscovery,
  findMatchingAgent,
  resolveAgentForIssue,
  matchAgentBySkill,
  createStubAgentCardFetcher,
  createPipelineAgentCardFetcher,

  // Structured logging
  createStructuredConsoleLogger,
  createStructuredBufferLogger,

  // Watch mode
  startWatch,
  type WatchOptions,
  type WatchHandle,

  // Runners
  CopilotRunner,
  type AgentRunner,
  type AgentContext,
  type AgentResult,

  // Agent orchestration
  createPipelineOrchestration,
  executePipelineOrchestration,
  validatePipelineHandoffs,
  sequential,
  parallel,
  hybrid,
  hierarchical,
  swarm,
  validateHandoff,
  simpleSchemaValidate,

  // Policy evaluators
  createPipelineRegoEvaluator,
  createPipelineCELEvaluator,
  createPipelineABACHook,
  createPipelineExpressionEvaluator,
  createPipelineLLMEvaluator,
  evaluatePipelineGate,
  scorePipelineComplexity,
  evaluatePipelineComplexityRouting,

  // Adapter ecosystem
  createPipelineAdapterRegistry,
  createPipelineWebhookBridge,
  resolveAdapterFromGit,
  resolveInfrastructure,
  scanPipelineAdapters,

  // Reconcilers — expose generalized names + backward-compat aliases
  createPipelineReconciler,
  createGateReconciler,
  createAutonomyReconciler,
  hasResourceChanged,
  fingerprintResource,

  // Extended audit
  createFileAuditLog,
  verifyAuditIntegrity,
  loadAuditEntries,
  rotateAuditLog,
  computeAuditHash,

  // Extended compliance
  checkFrameworkCompliance,
  getControlCatalog,
  getFrameworkMappings,
  listSupportedFrameworks,

  // Extended telemetry
  createSilentLogger,
  withPipelineSpanSync,
  getPipelineTracer,
  validateResourceSchema,

  // Orchestrator class & state store
  Orchestrator,
  type OrchestratorConfig,
  StateStore,
} from '@ai-sdlc/orchestrator';

// Backward-compatible reconciler aliases (dogfood used createDogfood* prefix)
export {
  createPipelineReconciler as createDogfoodPipelineReconciler,
  createGateReconciler as createDogfoodGateReconciler,
  createAutonomyReconciler as createDogfoodAutonomyReconciler,
} from '@ai-sdlc/orchestrator';

// Comprehensive type re-exports
export type {
  ApiVersion,
  Metadata,
  Condition,
  SecretRef,
  MetricCondition,
  Duration,
  Resource,
  TriggerFilter,
  Trigger,
  Provider,
  RoutingStrategy,
  ComplexityThreshold,
  Routing,
  Stage,
  PipelineSpec,
  PipelinePhase,
  PipelineStatus,
  Pipeline,
  AgentConstraints,
  HandoffContractRef,
  Handoff,
  SkillExample,
  Skill,
  AgentCard,
  AgentRoleSpec,
  AgentRoleStatus,
  AgentRole,
  GateScope,
  MetricRule,
  ToolRule,
  ReviewerRule,
  DocumentationRule,
  ProvenanceRule,
  ExpressionRule,
  GateRule,
  EnforcementLevel,
  Override,
  RetryPolicy,
  Evaluation,
  Gate,
  QualityGateSpec,
  QualityGateStatus,
  QualityGate,
  Permissions,
  ApprovalRequirement,
  Guardrails,
  MonitoringLevel,
  AutonomyLevel,
  PromotionCriteria as CorePromotionCriteria,
  DemotionTrigger,
  AgentAutonomyStatus,
  AutonomyPolicySpec,
  AutonomyPolicyStatus,
  AutonomyPolicy,
  AdapterInterface,
  HealthCheck,
  AdapterBindingSpec,
  AdapterBindingStatus,
  AdapterBinding,
  AnyResource,
  ResourceKind,
  ValidationError,
  GateVerdict,
  DemotionResult,
  ComplexityFactor,
  AuthorizationContext,
  AuthorizationResult,
  AuthIdentity,
  AuthenticationResult,
  Authenticator,
  MutatingGateContext,
  ExpressionEvaluator,
  ExpressionVerdict,
  LLMEvaluationDimension,
  LLMEvaluationResult,
  LLMGateVerdict,
  AgentExecutionState,
  HandoffValidationError,
  SchemaResolver,
  SchemaValidationError,
  MemoryTier,
  MemoryEntry,
  WorkingMemory,
  ShortTermMemory,
  LongTermMemory,
  SharedMemory,
  EpisodicMemory,
} from '@ai-sdlc/orchestrator';

// Resource builders (dogfood-specific — stay in this package)
export {
  buildDogfoodPipeline,
  buildDogfoodAgentRole,
  buildDogfoodQualityGate,
  buildDogfoodAutonomyPolicy,
  buildDogfoodAdapterBinding,
  PipelineBuilder,
  AgentRoleBuilder,
  QualityGateBuilder,
  AutonomyPolicyBuilder,
  AdapterBindingBuilder,
  parseBuilderManifest,
  validateBuilderManifest,
  API_VERSION,
} from './orchestrator/builders.js';
